name: Deploy to cloudtype
on:
    push:
        branches:
            - preview
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Connect deploy key
              uses: cloudtype-github-actions/connect@v1
              with:
                  token: ${{ secrets.CLOUDTYPE_TOKEN }}
                  ghtoken: ${{ secrets.GHP_TOKEN }}
            - name: Deploy
              uses: cloudtype-github-actions/deploy@v1
              with:
                  token: ${{ secrets.CLOUDTYPE_TOKEN }}
                  project: sjmh0507/green-maps
                  stage: beta1
                  yaml: >
                      name: green-maps

                      app: node@16

                      options:
                        env:
                          - name: PUPPETEER_SKIP_DOWNLOAD
                            value: "1"
                        ports: "2848"
                        start: node ./server/index.js
                      context:
                        git:
                          url: git@github.com:${{ github.repository }}.git
                          ref: ${{ github.ref }}
